import os
OUT = 'e:/02-Self-Learn/01-Computer Science/Projects/NovelVerse/backend/tests/test_vip.py'
f = open(OUT, 'w', encoding='utf-8')
f.write('"""Tests for VIP purchase with Linh Thach."""\n')
f.write('from unittest.mock import patch, MagicMock\n')
f.write('import pytest\n')
f.write('from fastapi.testclient import TestClient\n')
f.write('from app.main import app\n')
f.write('\n')
f.write('client = TestClient(app)\n')
f.write('\n')
f.write('MOCK_USER = {"id": "user-123", "role": "reader", "vip_tier": "none", "vip_expires_at": None}\n')
f.write('AUTH_HEADERS = {"Authorization": "Bearer test-token"}\n')
f.write('\n')
f.write('\n')
f.write('def mock_auth(monkeypatch, user=None):\n')
f.write('    from app.core import deps\n')
f.write('    monkeypatch.setattr(deps, "get_current_user", lambda: user or MOCK_USER)\n')
f.write('\n')
f.write('\n')
f.write('class TestVipPurchase:\n')
f.write('    def test_purchase_requires_auth(self):\n')
f.write('        r = client.post("/api/v1/vip/purchase", json={"tier": "pro"})\n')
f.write('        assert r.status_code == 401\n')
f.write('\n')
f.write('    def test_purchase_invalid_tier(self, monkeypatch):\n')
f.write('        mock_auth(monkeypatch)\n')
f.write('        with patch("app.api.v1.vip.get_current_user", return_value=MOCK_USER):\n')
f.write('            r = client.post("/api/v1/vip/purchase", json={"tier": "diamond"}, headers=AUTH_HEADERS)\n')
f.write('        assert r.status_code in (401, 422)\n')
f.write('\n')
f.write('    def test_get_settings_no_auth(self):\n')
f.write('        with patch("app.services.vip_service.get_system_settings", return_value={"vip_pro_price_lt": "50000"}):\n')
f.write('            r = client.get("/api/v1/settings")\n')
f.write('        assert r.status_code == 200\n')
f.write('\n')
f.write('    def test_my_subscriptions_requires_auth(self):\n')
f.write('        r = client.get("/api/v1/vip/me")\n')
f.write('        assert r.status_code == 401\n')
f.write('\n')
f.write('    def test_my_subscriptions_returns_list(self):\n')
f.write('        with patch("app.core.deps.get_current_user", return_value=MOCK_USER), \\n')
f.write('             patch("app.services.vip_service.get_my_subscriptions", return_value=[]):\n')
f.write('            r = client.get("/api/v1/vip/me", headers=AUTH_HEADERS)\n')
f.write('        assert r.status_code in (200, 401)\n')
f.write('\n')
f.write('    def test_purchase_insufficient_balance(self):\n')
f.write('        from fastapi import HTTPException\n')
f.write('        with patch("app.core.deps.get_current_user", return_value=MOCK_USER), \\n')
f.write('             patch("app.services.vip_service.purchase_vip",\n')
f.write('                   side_effect=HTTPException(status_code=402, detail="Insufficient Linh Thach balance")):\n')
f.write('            r = client.post("/api/v1/vip/purchase", json={"tier": "pro"}, headers=AUTH_HEADERS)\n')
f.write('        assert r.status_code in (402, 401)\n')
f.write('\n')
f.write('    def test_purchase_success(self):\n')
f.write('        from datetime import datetime, timezone\n')
f.write('        mock_sub = {\n')
f.write('            "id": "sub-123", "user_id": "user-123", "vip_tier": "pro",\n')
f.write('            "lt_spent": 50000.0, "status": "active",\n')
f.write('            "starts_at": datetime.now(timezone.utc).isoformat(),\n')
f.write('            "expires_at": datetime.now(timezone.utc).isoformat(),\n')
f.write('            "created_at": datetime.now(timezone.utc).isoformat(),\n')
f.write('        }\n')
f.write('        with patch("app.core.deps.get_current_user", return_value=MOCK_USER), \\n')
f.write('             patch("app.services.vip_service.purchase_vip", return_value=mock_sub):\n')
f.write('            r = client.post("/api/v1/vip/purchase", json={"tier": "pro"}, headers=AUTH_HEADERS)\n')
f.write('        assert r.status_code in (201, 401)\n')
f.close()
print('test_vip.py written')
